// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Firebase configuration for sport centre booking app across platforms
/// Auto-generated by FlutterFire CLI - reconfigure with 'flutterfire configure'
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Production Android configuration for Google Play Store distribution
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXo9zB1VQ239vCgzWpwhwcuwEfV5YwNMU',
    appId: '1:853313490143:android:6ef26bedb8e6803ac1ad6a',
    messagingSenderId: '853313490143',
    projectId: 'sportcentreapp',
    storageBucket: 'sportcentreapp.firebasestorage.app',
  );

  /// Web platform configuration for browser-based booking access
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXo9zB1VQ239vCgzWpwhwcuwEfV5YwNMU',
    appId: '1:853313490143:web:YOUR_WEB_APP_ID_HERE',
    messagingSenderId: '853313490143',
    projectId: 'sportcentreapp',
    storageBucket: 'sportcentreapp.firebasestorage.app',
    authDomain: 'sportcentreapp.firebaseapp.com',
  );
}
